'use client';
import Image from 'next/image';
import { useDeferredValue, useMemo, useState } from 'react';
import catalogData from '../data/catalog.json';
import wikiHiddenData from '../data/wiki-hidden.json';
import { ships as advancedShips } from '../data/ships';

type ApiShip={ship_id:number;ship_id_str:string;name:string;description:string;nation:string;type:string;tier:number;is_premium:boolean;is_special:boolean;price_credit:number;price_gold:number;images:{small:string;medium:string;large:string;contour:string}|null;default_profile:{hull?:{health?:number};engine?:{max_speed?:number};artillery?:{distance?:number;shot_delay?:number;max_dispersion?:number};concealment?:{detect_distance_by_ship?:number};torpedoes?:{torpedo_name?:string;reload_time?:number;rotation_time?:number;max_damage?:number;torpedo_speed?:number;distance?:number;visibility_dist?:number;slots?:Record<string,{name:string;barrels:number;guns:number;caliber:number}>}|null}|null};
type WikiHidden={dispersionType?:string;dispersionFormula?:string;sigma?:string;maxDispersion?:string;apDamage?:string;apVelocity?:string;apWeight?:string;fuse?:string;ricochetStart?:string;ricochetAlways?:string;normalization?:string;armingThreshold?:string;shells?:{type:string;name?:string;maxDamage?:string;fireChance?:string;velocity?:string;weight?:string;penetration?:string;fuse?:string;ricochetStart?:string;ricochetAlways?:string;normalization?:string;armingThreshold?:string}[];airGroups?:{type:string;options:{name:string;stats:Record<string,string>}[]}[];consumables?:{slot:number;name:string;icon:string;details:string}[];source:string;retrievedAt:string};
const catalog=(catalogData as ApiShip[]).filter(s=>s.images?.medium&&!s.name.startsWith('['));
const wikiHidden=wikiHiddenData as Record<string,WikiHidden>;
const nations:Record<string,string>={usa:'ABD',japan:'Japonya',ussr:'SSCB',germany:'Almanya',uk:'Birleşik Krallık',france:'Fransa',italy:'İtalya',pan_asia:'Pan-Asya',europe:'Avrupa',netherlands:'Hollanda',pan_america:'Pan-Amerika',spain:'İspanya',commonwealth:'Commonwealth'};
const nationFlags:Record<string,string>={usa:'🇺🇸',japan:'🇯🇵',ussr:'☭',germany:'🇩🇪',uk:'🇬🇧',france:'🇫🇷',italy:'🇮🇹',pan_asia:'◈',europe:'🇪🇺',netherlands:'🇳🇱',pan_america:'◉',spain:'🇪🇸',commonwealth:'◆'};
const nationFlagImages:Record<string,string>={usa:'https://wows-media-wowswiki-prod.wgcdn.co/1/1a/Wows_flag_USA_v3.png',japan:'https://wows-media-wowswiki-prod.wgcdn.co/7/74/Wows_flag_Japan_v3.png',ussr:'https://wows-media-wowswiki-prod.wgcdn.co/a/ad/Wows_flag_USSR_v3.png',germany:'https://wows-media-wowswiki-prod.wgcdn.co/a/a3/Wows_flag_Germany_v3.png',uk:'https://wows-media-wowswiki-prod.wgcdn.co/2/27/Wows_flag_UK_v3.png',france:'https://wows-media-wowswiki-prod.wgcdn.co/5/5c/Wows_flag_France_v3.png',italy:'https://wows-media-wowswiki-prod.wgcdn.co/5/5b/Wows_flag_Italy_v3.png',pan_asia:'https://wows-media-wowswiki-prod.wgcdn.co/7/73/Wows_flag_Pan_Asia_v3.png',europe:'https://wows-media-wowswiki-prod.wgcdn.co/c/c4/Wows_flag_Europe_v3.png',netherlands:'https://wows-media-wowswiki-prod.wgcdn.co/f/f2/Wows_flag_Netherlands_v3.png',pan_america:'https://wows-media-wowswiki-prod.wgcdn.co/d/d8/Wows_flag_Pan_America_v3.png',spain:'https://wows-media-wowswiki-prod.wgcdn.co/d/d4/Wows_flag_Spain_v3.png',commonwealth:'https://wows-media-wowswiki-prod.wgcdn.co/f/f3/Wows_flag_Commonwealth_v3.png'};
const classes:Record<string,string>={Battleship:'Zırhlı',Cruiser:'Kruvazör',Destroyer:'Muhrip',AirCarrier:'Uçak Gemisi',Submarine:'Denizaltı'};
const classIcons:Record<string,string>={Battleship:'https://wows-media-wowswiki-prod.wgcdn.co/d/d0/Icon_default_battleship.png',Cruiser:'https://wows-media-wowswiki-prod.wgcdn.co/3/37/Icon_default_cruiser.png',Destroyer:'https://wows-media-wowswiki-prod.wgcdn.co/4/46/Icon_default_destroyer.png',AirCarrier:'https://wows-media-wowswiki-prod.wgcdn.co/c/c5/Icon_default_aircarrier.png',Submarine:'https://wows-media-wowswiki-prod.wgcdn.co/0/07/Icon_default_submarine.png'};
const roman=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI'];
const techShips=catalog.filter(s=>!s.is_premium&&!s.is_special&&s.price_credit>0);
const superPredecessors:Record<string,string>={Satsuma:'Yamato',Yamagiri:'Shimakaze',Sekiryu:'Hakuryu',Annapolis:'Des Moines',Maine:'Montana','Joshua Humphreys':'Gearing','United States':'Midway','Admiral Ushakov':'Kremlin',Zorkiy:'Delny',Novosibirsk:'Petropavlovsk',Hannover:'Preussen',Clausewitz:'Hindenburg',Devastation:'Conqueror',Edgar:'Minotaur',Patrie:'République',Condé:'Henri IV',Piemonte:'Venezia',Dalarna:'Halland'};
const alternateTorpedoes:Record<string,{note:string;switchTime?:string;sets:{title:string;types:string[]}[]}>= {Yamagiri:{note:'Savaş sırasında yüklü torpido tüplerinin dolum durumunu koruyarak iki torpido tipi arasında geçiş yapabilir.',switchTime:'15 sn',sets:[{title:'8 / 20 KM DONANIMI',types:['Type F3 · 8 km · 76 knot · 21.367 hasar · 1,8 km tespit','Type 93 Improved · 20 km · 64 knot · 23.767 hasar · 2,5 km tespit']},{title:'12 / 20 KM DONANIMI',types:['Type 93 mod. 3 · 12 km · 67 knot · 23.767 hasar · 1,7 km tespit','Type 93 Improved · 20 km · 64 knot · 23.767 hasar · 2,5 km tespit']}]}};

export default function FleetApp(){
 const [nation,setNation]=useState('germany');
 const initial=catalog.find(s=>s.name==='Schlieffen')??techShips[0];
 const [selectedId,setSelectedId]=useState(initial.ship_id),[compare,setCompare]=useState<number[]>([]),[picker,setPicker]=useState(false),[query,setQuery]=useState(''),[detailTab,setDetailTab]=useState<'official'|'advanced'>('official');
 const deferredQuery=useDeferredValue(query),selected=catalog.find(s=>s.ship_id===selectedId)??initial;
 const nationFleet=useMemo(()=>techShips.filter(s=>s.nation===nation),[nation]);
 const nationPremium=useMemo(()=>catalog.filter(s=>s.nation===nation&&(s.is_premium||s.is_special)&&!s.name.startsWith('[')),[nation]);
 const results=useMemo(()=>{const q=deferredQuery.trim().toLowerCase();return catalog.filter(s=>!q||s.name.toLowerCase().includes(q)).slice(0,80)},[deferredQuery]);
 const compared=compare.map(id=>catalog.find(s=>s.ship_id===id)).filter((s):s is ApiShip=>Boolean(s));
 const advanced=advancedShips.find(s=>s.name.toLowerCase()===selected.name.toLowerCase()),wiki=wikiHidden[String(selected.ship_id)];
 const addCompare=(id:number)=>setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);
 const selectNation=(value:string)=>{setNation(value);const fleet=techShips.filter(s=>s.nation===value);if(fleet.length)setSelectedId(fleet[Math.floor(Math.random()*fleet.length)].ship_id)};
 return <main className="fleet-app"><NationRail active={nation} select={selectNation}/><div className="fleet-content">
  <header className="fleet-header"><a className="fleet-brand" href="#ust"><span>W</span><div><strong>WoWS <em>INTEL</em></strong><small>TAKTİK GEMİ VERİTABANI</small></div></a><nav><a href="#agac">TEKNOLOJİ AĞACI</a><a href="#gemi">GEMİ DOSYASI</a><button onClick={()=>setPicker(true)}>GEMİ ARA</button><a href="#karsilastir">KARŞILAŞTIR</a></nav><button className="compare-count" onClick={()=>setPicker(true)}>KARŞILAŞTIRMA <b>{compare.length}/3</b></button></header>
  <section className="fleet-hero" id="ust"><div className="hero-copy"><p>SEÇİLİ GEMİ / TIER {roman[selected.tier]} {classes[selected.type]}</p><h1>{selected.name}</h1><small>{nations[selected.nation]} donanmasının teknik dosyasını incele; port değerlerini ve gelişmiş savaş parametrelerini karşılaştır.</small><div><button onClick={()=>document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}>GEMİ DOSYASINI AÇ</button><button onClick={()=>setPicker(true)}>BAŞKA GEMİ SEÇ</button></div></div><div className="hero-ship"><Image src={selected.images!.large} alt={selected.name} fill priority sizes="(max-width: 760px) 100vw, 650px"/><span>{selected.name}</span></div></section>
  <section className="fleet-panel tech-panel" id="agac"><PanelTitle index="01" eyebrow={`${nationFlags[nation]} ${nations[nation]} DONANMASI`} title="Teknoloji ağacı" text="Sınıf hatlarını ve Tier ilerlemesini oyundaki düzene benzer biçimde incele."/><div className="nation-summary"><div><span>{nationFlags[nation]}</span><div><small>SEÇİLİ ULUS</small><b>{nations[nation]}</b></div></div><p>{nationFleet.length} araştırılabilir · {nationPremium.length} premium/özel gemi</p></div><div className="tier-row nation-tiers"><span>SINIF / TIER</span>{Array.from({length:11},(_,i)=>i+1).map(t=><b key={t}>{roman[t]}</b>)}</div><div className="nation-tree">{Object.entries(classes).map(([type,label])=>{const classShips=nationFleet.filter(s=>s.type===type);if(!classShips.length)return null;return <div className="class-line" key={type}><aside><span>{classIcon(type)}</span><b>{label}</b><small>{classShips.length} GEMİ</small></aside><div className="class-track">{Array.from({length:11},(_,i)=>i+1).map(t=><div className="tier-column" key={t}>{classShips.filter(s=>s.tier===t).map(s=><article className={`${selected.ship_id===s.ship_id?'active ':''}${s.tier===11?'super-ship':''}`} key={s.ship_id}>{s.tier===11&&superPredecessors[s.name]?<small className="predecessor">{superPredecessors[s.name]} →</small>:null}<button className="ship-select" onClick={()=>{setSelectedId(s.ship_id);document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}}><Image src={s.images!.medium} alt="" fill sizes="150px"/><strong>{s.name}</strong></button><button className={`tree-plus ${compare.includes(s.ship_id)?'added':''}`} onClick={()=>addCompare(s.ship_id)} aria-label={`${s.name} karşılaştırmaya ekle`}>{compare.includes(s.ship_id)?'✓':'+'}</button></article>)}</div>)}</div></div>})}</div><div className="premium-shelf"><header><div><span>★</span><div><b>PREMIUM / ÖZEL GEMİLER</b><small>{nations[nation]} · {nationPremium.length} GEMİ</small></div></div><p>Normal araştırma zincirinden bağımsızdır.</p></header><div className="premium-scroll">{nationPremium.sort((a,b)=>a.tier-b.tier||a.name.localeCompare(b.name)).map(s=><article className={selected.ship_id===s.ship_id?'active':''} key={s.ship_id}><button onClick={()=>{setSelectedId(s.ship_id);document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}}><Image src={s.images!.medium} alt="" fill sizes="160px"/><span>{roman[s.tier]}</span><strong>{s.name}</strong><small>{s.is_premium?'PREMIUM':'ÖZEL'} · {classes[s.type]}</small></button><button className={`tree-plus ${compare.includes(s.ship_id)?'added':''}`} onClick={()=>addCompare(s.ship_id)}>{compare.includes(s.ship_id)?'✓':'+'}</button></article>)}</div></div></section>
  <section className="fleet-panel ship-dossier" id="gemi"><div className="dossier-visual"><Image src={selected.images!.large} alt={`${selected.name} gemi görseli`} fill sizes="520px"/><span>{roman[selected.tier]}</span></div><div className="dossier-main"><p>{nations[selected.nation]} / {classes[selected.type]} / TIER {roman[selected.tier]}</p><h2>{selected.name}</h2><small>{selected.description}</small><div className="dossier-actions"><button onClick={()=>addCompare(selected.ship_id)}>{compare.includes(selected.ship_id)?'✓ KARŞILAŞTIRMADA':'+ KARŞILAŞTIRMAYA EKLE'}</button><button onClick={()=>setPicker(true)}>BAŞKA GEMİ SEÇ</button></div></div></section>
  <section className="fleet-panel data-panel"><div className="data-tabs"><button className={detailTab==='official'?'active':''} onClick={()=>setDetailTab('official')}><b>RESMÎ GEMİ VERİLERİ</b><span>Wargaming API</span></button><button className={detailTab==='advanced'?'active':''} onClick={()=>setDetailTab('advanced')}><b>GELİŞMİŞ / OYUN VERİLERİ</b><span>WoWS Wiki + oyun verisi</span></button></div>{detailTab==='official'?<OfficialDataExtended ship={selected}/>:<AdvancedDataWiki wiki={wiki} legacy={advanced}/>}</section>
  <section className="fleet-panel compare-section" id="karsilastir"><PanelTitle index="03" eyebrow="ANALİZ" title="Gemi karşılaştırması" action={<button onClick={()=>setPicker(true)}>+ GEMİ EKLE</button>}/>{compared.length?<div className="compare-modern"><div className="compare-labels-modern"><b>DEĞER</b>{['Can puanı','Azami hız','Ana batarya menzili','Dolum süresi','Azami dağılım','Denizden tespit'].map(x=><span key={x}>{x}</span>)}</div>{compared.map(s=><div className="compare-ship" key={s.ship_id}><b><Image src={s.images!.contour} alt="" width={110} height={34}/><span>{s.name}</span><button onClick={()=>addCompare(s.ship_id)}>×</button></b>{officialValues(s).map((v,i)=><span key={i}>{v}</span>)}</div>)}</div>:<div className="compare-empty"><b>Henüz gemi seçilmedi</b><span>En fazla üç gemiyi yan yana inceleyebilirsin.</span><button onClick={()=>setPicker(true)}>GEMİ ARA</button></div>}</section>
  <footer>WoWS Intel / Bağımsız teknik yardımcı · Wargaming ile bağlantılı değildir.</footer>
  {picker?<ShipPicker results={results} query={query} setQuery={setQuery} compare={compare} addCompare={addCompare} close={()=>setPicker(false)} select={id=>{setSelectedId(id);setPicker(false);document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}}/>:null}
 </div></main>
}

function NationRail({active,select}:{active:string;select:(nation:string)=>void}){return <aside className="nation-rail"><header><small>DONANMALAR</small><b>ULUS SEÇ</b></header><nav>{Object.entries(nations).map(([key,label])=><button className={active===key?'active':''} onClick={()=>select(key)} key={key} title={label}><span><Image src={nationFlagImages[key]} alt="" width={42} height={42}/></span><em>{label}</em></button>)}</nav></aside>}
function classIcon(type:string){return <Image src={classIcons[type]} alt="" width={27} height={27}/>}

function PanelTitle({index,eyebrow,title,text,action}:{index:string;eyebrow:string;title:string;text?:string;action?:React.ReactNode}){return <div className="panel-title"><div><span>{index}</span><div><small>{eyebrow}</small><h2>{title}</h2></div></div>{action??<p>{text}</p>}</div>}
function OfficialData({ship}:{ship:ApiShip}){const p=ship.default_profile;return <div className="data-groups"><DataGroup title="DAYANIKLILIK" rows={[['Can puanı',num(p?.hull?.health)],['Statü',ship.is_premium?'Premium':ship.is_special?'Özel':'Araştırılabilir'],['Kredi bedeli',num(ship.price_credit)]]}/><DataGroup title="HAREKETLİLİK" rows={[['Azami hız',unit(p?.engine?.max_speed,' knot')],['Tier',roman[ship.tier]],['Sınıf',classes[ship.type]]]}/><DataGroup title="ANA BATARYA" rows={[['Atış menzili',unit(p?.artillery?.distance,' km')],['Dolum süresi',unit(p?.artillery?.shot_delay,' sn')],['Azami dağılım',unit(p?.artillery?.max_dispersion,' m')]]}/><DataGroup title="GİZLİLİK" rows={[['Denizden tespit',unit(p?.concealment?.detect_distance_by_ship,' km')],['Kaynak','Wargaming API'],['Veri türü','Resmî']]}/></div>}
function AdvancedData({ship}:{ship:typeof advancedShips[number]|undefined}){if(!ship)return <div className="advanced-missing"><b>Gelişmiş veri eşleştirmesi hazırlanıyor</b><span>Bu geminin resmî port verileri kullanılabilir. Sigma, fuse ve mermi mekaniği verileri oyun sürümüyle eşleştirildikten sonra burada açılacak.</span></div>;return <div className="data-groups"><DataGroup title="DAĞILIM" rows={[['Sigma',String(ship.main.sigma)],['Dağılım ailesi',ship.main.dispersionType],['Formül',ship.main.dispersionFormula]]}/><DataGroup title="AP MERMİSİ" rows={[['İlk hız',`${ship.main.apVelocity} m/sn`],['Mermi ağırlığı',`${ship.main.apWeight} kg`],['Fuse',`${ship.main.fuse} sn`],['Kurma eşiği',`${ship.main.arming} mm`]]}/><DataGroup title="AÇILAR" rows={[['Sekme başlangıcı',`${ship.main.ricochetStart}°`],['Kesin sekme',`${ship.main.ricochetAlways}°`],['Normalizasyon',`${ship.main.normalization}°`],['Overmatch',`${ship.main.overmatch} mm`]]}/><DataGroup title="İKİNCİL BATARYA" rows={[['Temel menzil',`${ship.secondary.range} km`],...ship.secondary.mounts.map(m=>[`${m.caliber} mm`,`${m.reload} sn / ${m.penetration} mm`] as [string,string]),['Kaynak','Wiki + oyun verisi']]}/></div>}
function AdvancedDataWiki({wiki,legacy}:{wiki:WikiHidden|undefined;legacy:typeof advancedShips[number]|undefined}){if(!wiki&&!legacy)return <div className="advanced-missing"><b>Wiki sayfasında gelişmiş tablo bulunamadı</b><span>Doğrulanamayan hidden değerler tahmin edilerek gösterilmez.</span></div>;return <><div className="data-groups"><DataGroup title="DAĞILIM" rows={[["Sigma",wiki?.sigma??String(legacy?.main.sigma??'-')],["Dağılım ailesi",wiki?.dispersionType??legacy?.main.dispersionType??'-'],["Formül",wiki?.dispersionFormula??legacy?.main.dispersionFormula??'-'],["Azami dağılım",wiki?.maxDispersion?`${wiki.maxDispersion} m`:'-']]}/><DataGroup title="AP MERMİSİ" rows={[["Azami hasar",wiki?.apDamage??(legacy?legacy.main.apDamage.toLocaleString('tr-TR'):'-')],["İlk hız",wiki?.apVelocity?`${wiki.apVelocity} m/sn`:legacy?`${legacy.main.apVelocity} m/sn`:'-'],["Mermi ağırlığı",wiki?.apWeight?`${wiki.apWeight} kg`:legacy?`${legacy.main.apWeight} kg`:'-'],["Fuse",wiki?.fuse?`${wiki.fuse} sn`:legacy?`${legacy.main.fuse} sn`:'-'],["Kurma eşiği",wiki?.armingThreshold?`${wiki.armingThreshold} mm`:legacy?`${legacy.main.arming} mm`:'-']]}/><DataGroup title="AÇILAR" rows={[["Sekme başlangıcı",`${wiki?.ricochetStart??legacy?.main.ricochetStart??'-'}°`],["Kesin sekme",`${wiki?.ricochetAlways??legacy?.main.ricochetAlways??'-'}°`],["Normalizasyon",`${wiki?.normalization??legacy?.main.normalization??'-'}°`],["Overmatch",legacy?`${legacy.main.overmatch} mm`:'Kalibreye bağlı']]}/><DataGroup title="İKİNCİL / KAYNAK" rows={legacy?[["Temel ikincil menzil",`${legacy.secondary.range} km`],...legacy.secondary.mounts.map(m=>[`${m.caliber} mm`,`${m.reload} sn / ${m.penetration} mm`] as [string,string]),["Kaynak",wiki?'WoWS Wiki + oyun verisi':'Oyun verisi']]:[["İkincil batarya",'Ayrıntılı eşleştirme bekliyor'],["Kaynak",'WoWS Wiki'],["Alınma tarihi",wiki?.retrievedAt??'-']]}/></div>{wiki?<div className="source-strip"><span>Topluluk Wiki verisi · oyun güncellemeleriyle değişebilir</span><a href={wiki.source} target="_blank" rel="noreferrer">WIKI SAYFASINI AÇ</a></div>:null}</>}
function OfficialDataExtended({ship}:{ship:ApiShip}){const t=ship.default_profile?.torpedoes,w=wikiHidden[String(ship.ship_id)],special=alternateTorpedoes[ship.name];const rows:[string,string][]=t?[["Model",t.torpedo_name??'-'],["Düzen",torpedoLayout(t.slots)],["Menzil",unit(t.distance,' km')],["Hız",unit(t.torpedo_speed,' knot')],["Azami hasar",num(t.max_damage)],["Dolum süresi",unit(t.reload_time,' sn')],["Tespit mesafesi",unit(t.visibility_dist,' km')]]:[["Torpido","Bulunmuyor"]];return <><OfficialData ship={ship}/>{ship.type==='AirCarrier'?<AircraftGroups groups={w?.airGroups} tier={ship.tier}/>:null}<ShellGroup shells={w?.shells}/><div className="data-groups official-extra"><DataGroup title="TORPİDOLAR · WARGAMING API" rows={rows}/><ConsumableGroup items={w?.consumables}/></div>{special?<TorpedoMechanic data={special}/>:null}</>}
function AircraftGroups({groups,tier}:{groups:WikiHidden['airGroups'];tier:number}){if(!groups?.length)return <div className="advanced-missing"><b>Uçak filosu tablosu bulunamadı</b><span>Bu uçak gemisinin filo verileri Wiki ile eşleştirilemedi.</span></div>;return <section className="aircraft-groups"><header><div><small>UÇUŞ GRUBU DOSYASI · WOWS WIKI</small><h3>UÇAKLAR VE MÜHİMMAT</h3></div><span>{groups.length} FİLO TÜRÜ</span></header><div className="aircraft-grid">{groups.map((group,groupIndex)=><article className="aircraft-group" key={`${group.type}-${groupIndex}`}><h4>{airGroupName(group.type)}</h4><div className="aircraft-options">{group.options.map((option,index)=><section key={`${option.name}-${index}`}><header><b>{airOptionName(option.name)}</b>{index===group.options.length-1&&group.options.length>1?<small>ARAŞTIRILABİLİR</small>:null}</header>{Object.entries(option.stats).map(([label,value])=><div key={label}><span>{airStatName(label)}</span><b>{value}</b></div>)}</section>)}</div><AircraftConsumables type={group.type} tier={tier}/></article>)}</div></section>}
function AircraftConsumables({type,tier}:{type:string;tier:number}){const tactical=/TACTICAL/i.test(type);const fighter=tier>=10?`${tier===11?'7 uçak · 4 km · 20 sn':'7 uçak · 3,5 km · 60 sn'} · 3 şarj`:tier>=8?'5 uçak · 3 km · 60 sn · 3 şarj':tier>=6?'3 uçak · 2,5 km · 60 sn · 3 şarj':'Tier/filoya bağlı';return <div className="air-consumables"><small>FİLO SARF MALZEMELERİ</small>{tactical?<span>Taktik filolarda Motor Soğutma bulunmaz.</span>:<><span><b>Motor Soğutma</b> · motor takviyesini doldurur</span><span><b>Devriye Avcıları</b> · {fighter}</span></>}{/TORPEDO/i.test(type)?<span><b>Kaçınma Manevraları</b> · donatılmış filolarda uçak hasarını azaltır</span>:null}</div>}
function ShellGroup({shells}:{shells:WikiHidden['shells']}){if(!shells?.length)return null;return <div className="shell-groups"><h3>ANA BATARYA MERMİLERİ · WOWS WIKI</h3><div>{shells.map(shell=>{const rows=[["Azami hasar",shell.maxDamage??'-'],["Yangın ihtimali",shell.fireChance??(shell.type==='HE'?'—':'Uygulanmaz')],["İlk hız",shell.velocity?`${shell.velocity} m/sn`:'-'],["Ağırlık",shell.weight?`${shell.weight} kg`:'-'],["Deliş",shell.penetration?`${shell.penetration} mm`:shell.type==='AP'?'Mesafeye bağlı':'-'],["Fuse",shell.fuse?`${shell.fuse} sn`:'-']];return <article className={`shell-card ${shell.type.toLowerCase()}`} key={shell.type}><header><b>{shell.type}</b><span>{shell.name??'Mermi'}</span></header><div className="shell-stats">{rows.map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</div></article>})}</div></div>}
function TorpedoMechanic({data}:{data:{note:string;switchTime?:string;sets:{title:string;types:string[]}[]}}){return <section className="torpedo-mechanic"><header><div><small>ÖZEL SAVAŞ MEKANİĞİ</small><h3>DEĞİŞTİRİLEBİLİR TORPİDO TİPLERİ</h3></div>{data.switchTime?<b>GEÇİŞ: {data.switchTime}</b>:null}</header><p>{data.note}</p><div>{data.sets.map(set=><article key={set.title}><b>{set.title}</b>{set.types.map(type=><span key={type}>{type}</span>)}</article>)}</div></section>}
function ConsumableGroup({items}:{items:WikiHidden['consumables']}){const slots=items?Array.from(new Set(items.map(item=>item.slot))).map(slot=>[slot,items.filter(item=>item.slot===slot)] as const):[];return <article className="consumable-group"><h3>KULLANILABİLİR ÜRÜNLER · WOWS WIKI</h3>{slots.length?slots.map(([slot,options])=><section className="consumable-slot" key={slot}><header><b>{slot}. SLOT</b>{options.length>1?<small>ALTERNATİFLİ SEÇİM</small>:null}</header>{options.map((item,index)=><div className="consumable-row" key={`${item.slot}-${item.name}`}><Image src={item.icon} alt="" width={36} height={36}/><span><b>{consumableName(item.name)}</b><small>{localizeConsumableDetails(item.details)}</small></span>{index>0?<em>VEYA</em>:null}</div>)}</section>):<div><span>Ürün bilgisi</span><b>Bulunamadı</b></div>}</article>}
function DataGroup({title,rows}:{title:string;rows:[string,string][]}){return <article><h3>{title}</h3>{rows.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</article>}
function ShipPicker({results,query,setQuery,compare,addCompare,close,select}:{results:ApiShip[];query:string;setQuery:(v:string)=>void;compare:number[];addCompare:(id:number)=>void;close:()=>void;select:(id:number)=>void}){return <div className="picker-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><section className="ship-picker" role="dialog" aria-modal="true" aria-label="Gemi seç"><header><div><small>TÜM GEMİLER</small><h2>Gemi ara ve seç</h2></div><button onClick={close}>KAPAT ×</button></header><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Gemi adını yaz..."/><div className="picker-results">{results.map(s=><article key={s.ship_id}><button className="picker-select" onClick={()=>select(s.ship_id)}><Image src={s.images!.medium} alt="" fill sizes="240px"/><span>{roman[s.tier]}</span><div><b>{s.name}</b><small>{nations[s.nation]} / {classes[s.type]}</small></div></button><button className={compare.includes(s.ship_id)?'active':''} onClick={()=>addCompare(s.ship_id)}>{compare.includes(s.ship_id)?'✓':'+'}</button></article>)}</div></section></div>}
function officialValues(s:ApiShip){const p=s.default_profile;return[num(p?.hull?.health),unit(p?.engine?.max_speed,' knot'),unit(p?.artillery?.distance,' km'),unit(p?.artillery?.shot_delay,' sn'),unit(p?.artillery?.max_dispersion,' m'),unit(p?.concealment?.detect_distance_by_ship,' km')]}
function torpedoLayout(slots:Record<string,{name:string;barrels:number;guns:number;caliber:number}>|undefined){if(!slots)return '-';return Object.values(slots).map(s=>`${s.guns}×${s.barrels} ${s.caliber} mm`).join(' · ')}
function consumableName(name:string){const names:Record<string,string>={'Damage Control Party':'Hasar Kontrol Ekibi','Repair Party':'Onarım Ekibi','Hydroacoustic Search':'Hidroakustik Arama','Surveillance Radar':'Gözetleme Radarı','Smoke Generator':'Duman Jeneratörü','Main Battery Reload Booster':'Ana Batarya Yükleme Hızlandırıcısı','Engine Boost':'Motor Takviyesi','Defensive AA Fire':'Savunma Uçaksavar Ateşi','Catapult Fighter':'Avcı Uçağı','Spotting Aircraft':'Gözcü Uçağı','Torpedo Reload Booster':'Torpido Yükleme Hızlandırıcısı','Submarine Surveillance':'Denizaltı Gözetimi'};return names[name]??name}
function airGroupName(value:string){return value.replace(/ROCKET PLANES/i,'ROKET UÇAKLARI').replace(/ATTACK AIRCRAFT/i,'SALDIRI UÇAKLARI').replace(/TORPEDO BOMBERS/i,'TORPİDO BOMBARDIMAN UÇAKLARI').replace(/DIVE BOMBERS/i,'PİKE BOMBARDIMAN UÇAKLARI').replace(/SKIP BOMBERS/i,'SEKTİRMELİ BOMBA UÇAKLARI').replace(/TACTICAL/i,'TAKTİK').replace(/BOMBERS/i,'BOMBARDIMAN UÇAKLARI')}
function airOptionName(value:string){return value.replace(/STOCK/i,'STOK').replace(/RESEARCHABLE/i,'ARAŞTIRILABİLİR').replace(/STANDARD/i,'STANDART')}
function airStatName(value:string){const names:Record<string,string>={'Hit points':'Can puanı','Cruise speed (kt)':'Seyir hızı (knot)','Maximum speed (kt)':'Azami hız (knot)','Squadrons':'Filo sayısı','Aircraft per squadron':'Filodaki uçak','Squadron size':'Filo büyüklüğü','Size of attacking flight':'Saldırı kolundaki uçak','Aircraft on deck':'Güvertedeki uçak','Plane regeneration time (sec)':'Uçak yenilenme süresi (sn)','Preparation time (sec)':'Hazırlık süresi (sn)','Detectability (km)':'Tespit mesafesi (km)','Ammo name':'Mühimmat','Ammo type':'Mühimmat türü','Rockets in payload':'Uçak başına roket','Damage per rocket':'Roket hasarı','Armor penetration (mm)':'Zırh delişi (mm)','Fire chance (%)':'Yangın ihtimali (%)','Firing delay (sec)':'Atış gecikmesi (sn)','Torpedo name':'Torpido','Torpedoes in payload':'Uçak başına torpido','Torpedo damage':'Torpido hasarı','Flood chance (%)':'Su alma ihtimali (%)','Torpedo speed (kt)':'Torpido hızı (knot)','Arming distance (m)':'Kurulma mesafesi (m)','Torpedo range (km)':'Torpido menzili (km)','Bomb name':'Bomba','Bomb type':'Bomba türü','Bombs in payload':'Uçak başına bomba','Bomb damage':'Bomba hasarı'};return names[value]??value}
function localizeConsumableDetails(value:string){return value.replace(/charges?/gi,'şarj').replace(/action/gi,'etki').replace(/cooldown/gi,'bekleme').replace(/ship range/gi,'gemi menzili').replace(/torpedo range/gi,'torpido menzili').replace(/hp\/s/gi,'CP/sn').replace(/(\d(?:\.\d+)?)s\b/g,'$1 sn')}
function unit(v:number|undefined,u:string){return v==null?'-':`${v.toLocaleString('tr-TR',{maximumFractionDigits:2})}${u}`}
function num(v:number|undefined){return v==null?'-':v.toLocaleString('tr-TR')}
