'use client';
import Image from 'next/image';
import { useDeferredValue, useMemo, useState } from 'react';
import catalogData from '../data/catalog.json';
import wikiHiddenData from '../data/wiki-hidden.json';
import { ships as advancedShips } from '../data/ships';

type ApiShip={ship_id:number;ship_id_str:string;name:string;description:string;nation:string;type:string;tier:number;is_premium:boolean;is_special:boolean;price_credit:number;price_gold:number;images:{small:string;medium:string;large:string;contour:string}|null;default_profile:{hull?:{health?:number};engine?:{max_speed?:number};artillery?:{distance?:number;shot_delay?:number;max_dispersion?:number};concealment?:{detect_distance_by_ship?:number}}|null};
type WikiHidden={dispersionType?:string;dispersionFormula?:string;sigma?:string;maxDispersion?:string;apDamage?:string;apVelocity?:string;apWeight?:string;fuse?:string;ricochetStart?:string;ricochetAlways?:string;normalization?:string;armingThreshold?:string;source:string;retrievedAt:string};
const catalog=(catalogData as ApiShip[]).filter(s=>s.images?.medium);
const wikiHidden=wikiHiddenData as Record<string,WikiHidden>;
const nations:Record<string,string>={usa:'ABD',japan:'Japonya',ussr:'SSCB',germany:'Almanya',uk:'Birleşik Krallık',france:'Fransa',italy:'İtalya',pan_asia:'Pan-Asya',europe:'Avrupa',netherlands:'Hollanda',pan_america:'Pan-Amerika',spain:'İspanya',commonwealth:'Commonwealth'};
const nationFlags:Record<string,string>={usa:'🇺🇸',japan:'🇯🇵',ussr:'☭',germany:'🇩🇪',uk:'🇬🇧',france:'🇫🇷',italy:'🇮🇹',pan_asia:'◈',europe:'🇪🇺',netherlands:'🇳🇱',pan_america:'◉',spain:'🇪🇸',commonwealth:'◆'};
const classes:Record<string,string>={Battleship:'Zırhlı',Cruiser:'Kruvazör',Destroyer:'Muhrip',AirCarrier:'Uçak Gemisi',Submarine:'Denizaltı'};
const roman=['','I','II','III','IV','V','VI','VII','VIII','IX','X','XI'];
const techShips=catalog.filter(s=>!s.is_premium&&!s.is_special&&s.price_credit>0);

export default function FleetApp(){
 const [nation,setNation]=useState('germany');
 const initial=catalog.find(s=>s.name==='Schlieffen')??techShips[0];
 const [selectedId,setSelectedId]=useState(initial.ship_id),[compare,setCompare]=useState<number[]>([]),[picker,setPicker]=useState(false),[query,setQuery]=useState(''),[detailTab,setDetailTab]=useState<'official'|'advanced'>('official');
 const deferredQuery=useDeferredValue(query),selected=catalog.find(s=>s.ship_id===selectedId)??initial;
 const nationFleet=useMemo(()=>techShips.filter(s=>s.nation===nation),[nation]);
 const results=useMemo(()=>{const q=deferredQuery.trim().toLowerCase();return catalog.filter(s=>!q||s.name.toLowerCase().includes(q)).slice(0,80)},[deferredQuery]);
 const compared=compare.map(id=>catalog.find(s=>s.ship_id===id)).filter((s):s is ApiShip=>Boolean(s));
 const advanced=advancedShips.find(s=>s.name.toLowerCase()===selected.name.toLowerCase()),wiki=wikiHidden[String(selected.ship_id)];
 const addCompare=(id:number)=>setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);
 return <main className="fleet-app"><NationRail active={nation} select={value=>{setNation(value);document.getElementById('agac')?.scrollIntoView({behavior:'smooth'})}}/><div className="fleet-content">
  <header className="fleet-header"><a className="fleet-brand" href="#ust"><span>W</span><div><strong>WoWS <em>INTEL</em></strong><small>TAKTİK GEMİ VERİTABANI</small></div></a><nav><a href="#agac">TEKNOLOJİ AĞACI</a><a href="#gemi">GEMİ DOSYASI</a><button onClick={()=>setPicker(true)}>GEMİ ARA</button><a href="#karsilastir">KARŞILAŞTIR</a></nav><button className="compare-count" onClick={()=>setPicker(true)}>KARŞILAŞTIRMA <b>{compare.length}/3</b></button></header>
  <section className="fleet-hero" id="ust"><div className="hero-copy"><p>SEÇİLİ GEMİ / TIER {roman[selected.tier]} {classes[selected.type]}</p><h1>{selected.name}</h1><small>{nations[selected.nation]} donanmasının teknik dosyasını incele; port değerlerini ve gelişmiş savaş parametrelerini karşılaştır.</small><div><button onClick={()=>document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}>GEMİ DOSYASINI AÇ</button><button onClick={()=>setPicker(true)}>BAŞKA GEMİ SEÇ</button></div></div><div className="hero-ship"><Image src={selected.images!.large} alt={selected.name} fill priority sizes="(max-width: 760px) 100vw, 650px"/><span>{selected.name}</span></div></section>
  <section className="fleet-panel tech-panel" id="agac"><PanelTitle index="01" eyebrow={`${nationFlags[nation]} ${nations[nation]} DONANMASI`} title="Teknoloji ağacı" text="Sınıf hatlarını ve Tier ilerlemesini oyundaki düzene benzer biçimde incele."/><div className="nation-summary"><div><span>{nationFlags[nation]}</span><div><small>SEÇİLİ ULUS</small><b>{nations[nation]}</b></div></div><p>{nationFleet.length} araştırılabilir gemi · 5 sınıf hattı</p></div><div className="tier-row nation-tiers"><span>SINIF / TIER</span>{Array.from({length:11},(_,i)=>i+1).map(t=><b key={t}>{roman[t]}</b>)}</div><div className="nation-tree">{Object.entries(classes).map(([type,label])=>{const classShips=nationFleet.filter(s=>s.type===type);if(!classShips.length)return null;return <div className="class-line" key={type}><aside><span>{classIcon(type)}</span><b>{label}</b><small>{classShips.length} GEMİ</small></aside><div className="class-track">{Array.from({length:11},(_,i)=>i+1).map(t=><div className="tier-column" key={t}>{classShips.filter(s=>s.tier===t).map(s=><article className={selected.ship_id===s.ship_id?'active':''} key={s.ship_id}><button className="ship-select" onClick={()=>{setSelectedId(s.ship_id);document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}}><Image src={s.images!.medium} alt="" fill sizes="150px"/><strong>{s.name}</strong></button><button className={`tree-plus ${compare.includes(s.ship_id)?'added':''}`} onClick={()=>addCompare(s.ship_id)} aria-label={`${s.name} karşılaştırmaya ekle`}>{compare.includes(s.ship_id)?'✓':'+'}</button></article>)}</div>)}</div></div>})}</div></section>
  <section className="fleet-panel ship-dossier" id="gemi"><div className="dossier-visual"><Image src={selected.images!.large} alt={`${selected.name} gemi görseli`} fill sizes="520px"/><span>{roman[selected.tier]}</span></div><div className="dossier-main"><p>{nations[selected.nation]} / {classes[selected.type]} / TIER {roman[selected.tier]}</p><h2>{selected.name}</h2><small>{selected.description}</small><div className="dossier-actions"><button onClick={()=>addCompare(selected.ship_id)}>{compare.includes(selected.ship_id)?'✓ KARŞILAŞTIRMADA':'+ KARŞILAŞTIRMAYA EKLE'}</button><button onClick={()=>setPicker(true)}>BAŞKA GEMİ SEÇ</button></div></div></section>
  <section className="fleet-panel data-panel"><div className="data-tabs"><button className={detailTab==='official'?'active':''} onClick={()=>setDetailTab('official')}><b>RESMÎ GEMİ VERİLERİ</b><span>Wargaming API</span></button><button className={detailTab==='advanced'?'active':''} onClick={()=>setDetailTab('advanced')}><b>GELİŞMİŞ / OYUN VERİLERİ</b><span>WoWS Wiki + oyun verisi</span></button></div>{detailTab==='official'?<OfficialData ship={selected}/>:<AdvancedDataWiki wiki={wiki} legacy={advanced}/>}</section>
  <section className="fleet-panel compare-section" id="karsilastir"><PanelTitle index="03" eyebrow="ANALİZ" title="Gemi karşılaştırması" action={<button onClick={()=>setPicker(true)}>+ GEMİ EKLE</button>}/>{compared.length?<div className="compare-modern"><div className="compare-labels-modern"><b>DEĞER</b>{['Can puanı','Azami hız','Ana batarya menzili','Dolum süresi','Azami dağılım','Denizden tespit'].map(x=><span key={x}>{x}</span>)}</div>{compared.map(s=><div className="compare-ship" key={s.ship_id}><b><Image src={s.images!.contour} alt="" width={110} height={34}/><span>{s.name}</span><button onClick={()=>addCompare(s.ship_id)}>×</button></b>{officialValues(s).map((v,i)=><span key={i}>{v}</span>)}</div>)}</div>:<div className="compare-empty"><b>Henüz gemi seçilmedi</b><span>En fazla üç gemiyi yan yana inceleyebilirsin.</span><button onClick={()=>setPicker(true)}>GEMİ ARA</button></div>}</section>
  <footer>WoWS Intel / Bağımsız teknik yardımcı · Wargaming ile bağlantılı değildir.</footer>
  {picker?<ShipPicker results={results} query={query} setQuery={setQuery} compare={compare} addCompare={addCompare} close={()=>setPicker(false)} select={id=>{setSelectedId(id);setPicker(false);document.getElementById('gemi')?.scrollIntoView({behavior:'smooth'})}}/>:null}
 </div></main>
}

function NationRail({active,select}:{active:string;select:(nation:string)=>void}){return <aside className="nation-rail"><header><small>DONANMALAR</small><b>ULUS SEÇ</b></header><nav>{Object.entries(nations).map(([key,label])=><button className={active===key?'active':''} onClick={()=>select(key)} key={key} title={label}><span>{nationFlags[key]}</span><em>{label}</em></button>)}</nav></aside>}
function classIcon(type:string){return type==='Battleship'?'▰':type==='Cruiser'?'◆':type==='Destroyer'?'➤':type==='AirCarrier'?'▱':'◒'}

function PanelTitle({index,eyebrow,title,text,action}:{index:string;eyebrow:string;title:string;text?:string;action?:React.ReactNode}){return <div className="panel-title"><div><span>{index}</span><div><small>{eyebrow}</small><h2>{title}</h2></div></div>{action??<p>{text}</p>}</div>}
function OfficialData({ship}:{ship:ApiShip}){const p=ship.default_profile;return <div className="data-groups"><DataGroup title="DAYANIKLILIK" rows={[['Can puanı',num(p?.hull?.health)],['Statü',ship.is_premium?'Premium':ship.is_special?'Özel':'Araştırılabilir'],['Kredi bedeli',num(ship.price_credit)]]}/><DataGroup title="HAREKETLİLİK" rows={[['Azami hız',unit(p?.engine?.max_speed,' knot')],['Tier',roman[ship.tier]],['Sınıf',classes[ship.type]]]}/><DataGroup title="ANA BATARYA" rows={[['Atış menzili',unit(p?.artillery?.distance,' km')],['Dolum süresi',unit(p?.artillery?.shot_delay,' sn')],['Azami dağılım',unit(p?.artillery?.max_dispersion,' m')]]}/><DataGroup title="GİZLİLİK" rows={[['Denizden tespit',unit(p?.concealment?.detect_distance_by_ship,' km')],['Kaynak','Wargaming API'],['Veri türü','Resmî']]}/></div>}
function AdvancedData({ship}:{ship:typeof advancedShips[number]|undefined}){if(!ship)return <div className="advanced-missing"><b>Gelişmiş veri eşleştirmesi hazırlanıyor</b><span>Bu geminin resmî port verileri kullanılabilir. Sigma, fuse ve mermi mekaniği verileri oyun sürümüyle eşleştirildikten sonra burada açılacak.</span></div>;return <div className="data-groups"><DataGroup title="DAĞILIM" rows={[['Sigma',String(ship.main.sigma)],['Dağılım ailesi',ship.main.dispersionType],['Formül',ship.main.dispersionFormula]]}/><DataGroup title="AP MERMİSİ" rows={[['İlk hız',`${ship.main.apVelocity} m/sn`],['Mermi ağırlığı',`${ship.main.apWeight} kg`],['Fuse',`${ship.main.fuse} sn`],['Kurma eşiği',`${ship.main.arming} mm`]]}/><DataGroup title="AÇILAR" rows={[['Sekme başlangıcı',`${ship.main.ricochetStart}°`],['Kesin sekme',`${ship.main.ricochetAlways}°`],['Normalizasyon',`${ship.main.normalization}°`],['Overmatch',`${ship.main.overmatch} mm`]]}/><DataGroup title="İKİNCİL BATARYA" rows={[['Temel menzil',`${ship.secondary.range} km`],...ship.secondary.mounts.map(m=>[`${m.caliber} mm`,`${m.reload} sn / ${m.penetration} mm`] as [string,string]),['Kaynak','Wiki + oyun verisi']]}/></div>}
function AdvancedDataWiki({wiki,legacy}:{wiki:WikiHidden|undefined;legacy:typeof advancedShips[number]|undefined}){if(!wiki&&!legacy)return <div className="advanced-missing"><b>Wiki sayfasında gelişmiş tablo bulunamadı</b><span>Doğrulanamayan hidden değerler tahmin edilerek gösterilmez.</span></div>;return <><div className="data-groups"><DataGroup title="DAĞILIM" rows={[["Sigma",wiki?.sigma??String(legacy?.main.sigma??'-')],["Dağılım ailesi",wiki?.dispersionType??legacy?.main.dispersionType??'-'],["Formül",wiki?.dispersionFormula??legacy?.main.dispersionFormula??'-'],["Azami dağılım",wiki?.maxDispersion?`${wiki.maxDispersion} m`:'-']]}/><DataGroup title="AP MERMİSİ" rows={[["Azami hasar",wiki?.apDamage??(legacy?legacy.main.apDamage.toLocaleString('tr-TR'):'-')],["İlk hız",wiki?.apVelocity?`${wiki.apVelocity} m/sn`:legacy?`${legacy.main.apVelocity} m/sn`:'-'],["Mermi ağırlığı",wiki?.apWeight?`${wiki.apWeight} kg`:legacy?`${legacy.main.apWeight} kg`:'-'],["Fuse",wiki?.fuse?`${wiki.fuse} sn`:legacy?`${legacy.main.fuse} sn`:'-'],["Kurma eşiği",wiki?.armingThreshold?`${wiki.armingThreshold} mm`:legacy?`${legacy.main.arming} mm`:'-']]}/><DataGroup title="AÇILAR" rows={[["Sekme başlangıcı",`${wiki?.ricochetStart??legacy?.main.ricochetStart??'-'}°`],["Kesin sekme",`${wiki?.ricochetAlways??legacy?.main.ricochetAlways??'-'}°`],["Normalizasyon",`${wiki?.normalization??legacy?.main.normalization??'-'}°`],["Overmatch",legacy?`${legacy.main.overmatch} mm`:'Kalibreye bağlı']]}/><DataGroup title="İKİNCİL / KAYNAK" rows={legacy?[["Temel ikincil menzil",`${legacy.secondary.range} km`],...legacy.secondary.mounts.map(m=>[`${m.caliber} mm`,`${m.reload} sn / ${m.penetration} mm`] as [string,string]),["Kaynak",wiki?'WoWS Wiki + oyun verisi':'Oyun verisi']]:[["İkincil batarya",'Ayrıntılı eşleştirme bekliyor'],["Kaynak",'WoWS Wiki'],["Alınma tarihi",wiki?.retrievedAt??'-']]}/></div>{wiki?<div className="source-strip"><span>Topluluk Wiki verisi · oyun güncellemeleriyle değişebilir</span><a href={wiki.source} target="_blank" rel="noreferrer">WIKI SAYFASINI AÇ</a></div>:null}</>}
function DataGroup({title,rows}:{title:string;rows:[string,string][]}){return <article><h3>{title}</h3>{rows.map(([l,v])=><div key={l}><span>{l}</span><b>{v}</b></div>)}</article>}
function ShipPicker({results,query,setQuery,compare,addCompare,close,select}:{results:ApiShip[];query:string;setQuery:(v:string)=>void;compare:number[];addCompare:(id:number)=>void;close:()=>void;select:(id:number)=>void}){return <div className="picker-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><section className="ship-picker" role="dialog" aria-modal="true" aria-label="Gemi seç"><header><div><small>TÜM GEMİLER</small><h2>Gemi ara ve seç</h2></div><button onClick={close}>KAPAT ×</button></header><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Gemi adını yaz..."/><div className="picker-results">{results.map(s=><article key={s.ship_id}><button className="picker-select" onClick={()=>select(s.ship_id)}><Image src={s.images!.medium} alt="" fill sizes="240px"/><span>{roman[s.tier]}</span><div><b>{s.name}</b><small>{nations[s.nation]} / {classes[s.type]}</small></div></button><button className={compare.includes(s.ship_id)?'active':''} onClick={()=>addCompare(s.ship_id)}>{compare.includes(s.ship_id)?'✓':'+'}</button></article>)}</div></section></div>}
function officialValues(s:ApiShip){const p=s.default_profile;return[num(p?.hull?.health),unit(p?.engine?.max_speed,' knot'),unit(p?.artillery?.distance,' km'),unit(p?.artillery?.shot_delay,' sn'),unit(p?.artillery?.max_dispersion,' m'),unit(p?.concealment?.detect_distance_by_ship,' km')]}
function unit(v:number|undefined,u:string){return v==null?'-':`${v.toLocaleString('tr-TR',{maximumFractionDigits:2})}${u}`}
function num(v:number|undefined){return v==null?'-':v.toLocaleString('tr-TR')}
