'use client';
import { useMemo, useState } from 'react';
import { ships, Ship } from '../data/ships';

type Build = { secondarySkill:boolean; secondaryUpgrade:boolean; mainReloadUpgrade:boolean; concealment:boolean; combat:boolean };
const initialBuild:Build={secondarySkill:false,secondaryUpgrade:false,mainReloadUpgrade:false,concealment:false,combat:false};
const roman:Record<number,string>={9:'IX',10:'X'};
const fmt=(v:number,d=1)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v);

function ShipMark({ship}:{ship:Ship}){return <div className="ship-mark" aria-hidden="true"><span/><span/><span/><i>{ship.main.guns}</i></div>}
function Group({title,children}:{title:string;children:React.ReactNode}){return <article className="stat-group"><h3>{title}</h3>{children}</article>}
function Stat({label,value,accent=false}:{label:string;value:string;accent?:boolean}){return <div className="stat-row"><span>{label}</span><strong className={accent?'accent':''}>{value}</strong></div>}
function Toggle({active,onChange,title,detail}:{active:boolean;onChange:()=>void;title:string;detail:string}){return <button className={`build-option ${active?'active':''}`} onClick={onChange} aria-pressed={active}><span className="check">{active?'OK':''}</span><span><strong>{title}</strong><small>{detail}</small></span></button>}

export default function Home(){
 const [selectedId,setSelectedId]=useState('libertad');
 const [compare,setCompare]=useState<string[]>(['los-andes','libertad']);
 const [build,setBuild]=useState<Build>(initialBuild);
 const selected=ships.find(s=>s.id===selectedId)??ships[0];
 const compared=compare.map(id=>ships.find(s=>s.id===id)).filter((s):s is Ship=>Boolean(s));
 const calc=useMemo(()=>{const range=(build.secondarySkill?1.2:1)*(build.secondaryUpgrade?1.2:1)*(build.combat&&selected.nation==='Pan-America'?1.2:1);const secReload=build.combat&&selected.nation==='Pan-America'?(selected.id==='libertad'?0.8:0.85):1;return{secondaryRange:selected.secondary.range*range,mainReload:selected.main.reload*(build.mainReloadUpgrade?0.88:1),concealment:selected.concealment*(build.concealment?0.9:1),secondaryReloads:selected.secondary.mounts.map(m=>m.reload*secReload)}},[build,selected]);
 const toggleCompare=(id:string)=>setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);
 const toggleBuild=(key:keyof Build)=>setBuild(v=>({...v,[key]:!v[key]}));
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-icon">W</span><span><strong>WoWS <em>INTEL</em></strong><small>TACTICAL SHIP DATABASE</small></span></a><nav><a className="active" href="#tree">TECH TREE</a><a href="#inspector">SHIP INSPECTOR</a><a href="#build">BUILD LAB</a><a href="#compare">COMPARE</a></nav><div className="header-status"><span><i/> DATA: VERIFIED</span><b>{compare.length}<small>/3</small></b></div></header>
  <section className="hero" id="top"><div><p className="eyebrow">NAVAL INTELLIGENCE / LIVE BUILD 01</p><h1>Know the ship.<br/><span>Win the angle.</span></h1><p>Hidden parameters, live build calculations and clean side-by-side comparison for World of Warships.</p></div><div className="radar" aria-hidden="true"><span/><span/><span/><i/></div></section>
  <section className="tech-tree frame" id="tree"><div className="section-heading"><div><span className="index">01</span><div><p className="eyebrow">RESEARCH BUREAU</p><h2>Technology tree</h2></div></div><p>Select a ship to open its technical dossier.</p></div><div className="tier-head"><span>NATION / LINE</span>{[6,7,8,9,10].map(t=><b key={t}>{roman[t]??t}</b>)}</div>
   {(['Pan-America','Germany'] as const).map(n=><div className="tree-row" key={n}><aside><span className={`flag ${n==='Germany'?'germany':''}`}>{n==='Germany'?'DE':'PA'}</span><div><strong>{n}</strong><small>{n==='Germany'?'BATTLECRUISERS':'BATTLESHIPS'}</small></div></aside><div className="tree-track">{[6,7,8,9,10].map(t=>{const s=ships.find(x=>x.nation===n&&x.tier===t);return <div className="tree-slot" key={t}>{s?<button className={selected.id===s.id?'selected':''} onClick={()=>setSelectedId(s.id)}><ShipMark ship={s}/><span><small>TIER {roman[t]}</small><strong>{s.name}</strong><em>{s.main.layout} / {s.main.caliber} MM</em></span></button>:<i/>}</div>})}</div></div>)}
  </section>
  <section className="inspector frame" id="inspector"><div className="ship-hero"><div className="ship-watermark"><span>{selected.nationCode}</span><ShipMark ship={selected}/></div><div className="ship-title"><p className="eyebrow">{selected.nation} / TIER {roman[selected.tier]} / {selected.shipClass}</p><h2>{selected.name}</h2><p>{selected.description}</p><div className="feature-list">{selected.features.map(x=><span key={x}>{x}</span>)}</div></div><button className={`compare-button ${compare.includes(selected.id)?'active':''}`} onClick={()=>toggleCompare(selected.id)}>{compare.includes(selected.id)?'OK IN COMPARISON':'+ ADD TO COMPARISON'}</button></div>
   <div className="dossier"><Group title="SURVIVABILITY & MOBILITY"><Stat label="Hit points" value={selected.hp.toLocaleString('en-US')}/><Stat label="Maximum speed" value={`${fmt(selected.speed)} kn`}/><Stat label="Turning circle" value={`${selected.turningRadius} m`}/><Stat label="Rudder shift" value={`${fmt(selected.rudderShift)} s`}/><Stat label="Calculated concealment" value={`${fmt(calc.concealment,2)} km`} accent={build.concealment}/></Group><Group title="MAIN BATTERY"><Stat label="Arrangement" value={`${selected.main.layout} / ${selected.main.caliber} mm`}/><Stat label="Firing range" value={`${fmt(selected.main.range,2)} km`}/><Stat label="Calculated reload" value={`${fmt(calc.mainReload,2)} s`} accent={build.mainReloadUpgrade}/><Stat label="Sigma" value={fmt(selected.main.sigma)}/><Stat label="Max. dispersion" value={`${selected.main.maxDispersion} m`}/><Stat label="Formula" value={selected.main.dispersionFormula}/></Group><Group title="AP BALLISTICS"><Stat label="Maximum damage" value={selected.main.apDamage.toLocaleString('en-US')}/><Stat label="Muzzle velocity" value={`${selected.main.apVelocity} m/s`}/><Stat label="Shell weight" value={`${selected.main.apWeight} kg`}/><Stat label="Fuse time" value={`${selected.main.fuse} s`}/><Stat label="Arming threshold" value={`${selected.main.arming} mm`}/><Stat label="Ricochet angles" value={`${selected.main.ricochetStart} deg to ${selected.main.ricochetAlways} deg`}/><Stat label="Overmatch" value={`${selected.main.overmatch} mm`}/></Group><Group title="SECONDARY BATTERY"><Stat label="Calculated range" value={`${fmt(calc.secondaryRange,2)} km`} accent={calc.secondaryRange!==selected.secondary.range}/>{selected.secondary.mounts.map((m,i)=><div className="mount" key={m.caliber}><b>{m.caliber} MM HE</b><Stat label="Reload" value={`${fmt(calc.secondaryReloads[i],2)} s`} accent={calc.secondaryReloads[i]!==m.reload}/><Stat label="Penetration" value={`${m.penetration} mm`}/><Stat label="Velocity" value={`${m.velocity} m/s`}/></div>)}</Group></div><div className="source-strip"><span>Official-reference dataset / values may change with game updates</span><a href={selected.source} target="_blank" rel="noreferrer">OPEN SHIP SOURCE </a></div>
  </section>
  <section className="build-lab frame" id="build"><div className="section-heading"><div><span className="index">02</span><div><p className="eyebrow">CONFIGURATION ENGINE</p><h2>Live build lab</h2></div></div><button className="reset" onClick={()=>setBuild(initialBuild)}>RESET BUILD</button></div><div className="build-grid"><Toggle active={build.secondarySkill} onChange={()=>toggleBuild('secondarySkill')} title="Long-Range Secondary Battery Shells" detail="Commander skill / +20% secondary range"/><Toggle active={build.secondaryUpgrade} onChange={()=>toggleBuild('secondaryUpgrade')} title="Secondary Battery Modification 1" detail="Upgrade / +20% secondary range"/><Toggle active={build.mainReloadUpgrade} onChange={()=>toggleBuild('mainReloadUpgrade')} title="Main Battery Modification 3" detail="Upgrade / -12% main battery reload"/><Toggle active={build.concealment} onChange={()=>toggleBuild('concealment')} title="Concealment Expert" detail="Commander skill / -10% detectability"/>{selected.nation==='Pan-America'&&<Toggle active={build.combat} onChange={()=>toggleBuild('combat')} title="Modified Secondary Munitions" detail={`Combat Instructions / +20% range / -${selected.id==='libertad'?20:15}% reload`}/>}</div><div className="live-output"><span>LIVE OUTPUT</span><div><small>MAIN RELOAD</small><strong>{fmt(calc.mainReload,2)}<em>s</em></strong></div><div><small>SECONDARY RANGE</small><strong>{fmt(calc.secondaryRange,2)}<em>km</em></strong></div><div><small>CONCEALMENT</small><strong>{fmt(calc.concealment,2)}<em>km</em></strong></div></div></section>
  <section className="comparison frame" id="compare"><div className="section-heading"><div><span className="index">03</span><div><p className="eyebrow">SIDE-BY-SIDE</p><h2>Ship comparison</h2></div></div><p>{compare.length} / 3 ships selected</p></div><div className="compare-table"><div className="compare-labels"><b>PARAMETER</b>{['Hit points','Top speed','Main battery','Reload','Sigma','AP damage','AP velocity','Overmatch','Secondary range','Concealment'].map(x=><span key={x}>{x}</span>)}</div>{compared.map(s=><div className="compare-column" key={s.id}><b><span>{roman[s.tier]}</span>{s.name}<button onClick={()=>toggleCompare(s.id)} aria-label={`Remove ${s.name}`}>x</button></b><span>{s.hp.toLocaleString('en-US')}</span><span>{fmt(s.speed)} kn</span><span>{s.main.guns} x {s.main.caliber} mm</span><span>{fmt(s.main.reload)} s</span><span>{fmt(s.main.sigma)}</span><span>{s.main.apDamage.toLocaleString('en-US')}</span><span>{s.main.apVelocity} m/s</span><span>{s.main.overmatch} mm</span><span>{fmt(s.secondary.range)} km</span><span>{fmt(s.concealment)} km</span></div>)}{compare.length<3&&<button className="empty-column" onClick={()=>{const s=ships.find(x=>!compare.includes(x.id));if(s)toggleCompare(s.id)}}><span>+</span>ADD SHIP</button>}</div></section>
  <footer><a className="brand" href="#top"><span className="brand-icon">W</span><strong>WoWS <em>INTEL</em></strong></a><p>Independent technical companion. Not affiliated with Wargaming.</p><span>PROTOTYPE / BUILD 01</span></footer>
 </main>
}
